### ISSUE TITLE
Fix sizing of bottom row of member logos 

### ISSUE THREAD

**Issue by danamlewis** [TCNCoalition/website#26]
Top row correctly contextualized size to each other, bottom row varying sizes:

![image](https://user-images.githubusercontent.com/7468165/78930378-da83c180-7a58-11ea-9bfb-8625864c607c.png)

**Comment by kreativmonkey** [comment]
there is no size to fix, in the members file i describe the correct size of the logo but not everyone read this information...

**Comment by dijour** [comment]
I think the correct way to do this would be to account for it in CSS... trying to wrangle every different member to properly submit PNGs is tough.

**Comment by kreativmonkey** [comment]
Not really. I know it will work with css, but I think we should prefer the right size, because it will make the file size for downloading/displaying much smaller! But i will have a look at this later on.

**Comment by dijour** [comment]
Do you currently allow SVG? That would solve a lot of problems.

**Comment by harperreed** [comment]
SVG would be best.

**Comment by dijour** [comment]
> SVG would be best.

Of course! Let's please standardize if possible. Would make our images look much better across a range of devices, as well as load faster. Even opens up the possibility of SVG animations, if we want to get fancy 😄

**Comment by kreativmonkey** [comment]
Yes SVG is nice, but SVG need to implement in a different way to normal image files. 

We can do it with the switch in the mebres.yml like:

```yaml
- organization: ito
  country: Germany
  logo: images/members/ito-logo.svg
  svg: true
  url: https://www.ito-app.org/
```

ore

```yaml
- organization: ito
  country: Germany
  logo: 
     png: images/members/ito-logo.png
     svg: images/members/ito-logo.svg
  url: https://www.ito-app.org/
```

ore 

```yaml
- organization: ito
  country: Germany
  logo: images/members/ito-logo.png
  svg-logo: image/members/ito-logo.svg
  url: https://www.ito-app.org/
```
```yaml
- organization: ito
  country: Germany
  logo: 
    file: images/members/ito-logo.png
    type: svg
  url: https://www.ito-app.org/
```

i don't know wich is the best....
